name: CI Training       # שם ה-Workflow (מופיע בלשונית Actions)

on:                     # מתי לרוץ?
  push:
    branches:
      - master          # בכל דחיפה ל-master

jobs:
  build:                # שם ה-Job
    runs-on: ubuntu-latest  # השרת שיריץ את העבודה

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # מוריד את הקוד מה-Repo לשרת

    - name: Run my script
      run: python main.py        # מריץ את הפקודה
    
    - name: Run Tests
      run: echo "Running Tests..."

    - name: Build something
      run: echo "This is my app" > my-app.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # הפעולה הרשמית להעלאה
      with:
        name: my-super-artifact         # השם שניתן לקופסה באחסון
        path: my-app.txt                # הנתיב לקובץ שאנחנו רוצים לשמור
